# Generated by Django 2.1.5 on 2019-01-24 12:06

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('development', 'development'), ('workout', 'workout'), ('cooking', 'cooking')], max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, default='')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='development/thumbnail/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
    ]
